# Generated by Django 5.0.4 on 2024-04-03 18:56

from django.db import migrations
from django.contrib.auth.models import Group

grupos = ['Instituicao', 'Docente']

def load_initial_data(apps, schema_editor):
    for grupo in grupos:
        meu_grupo=Group.objects.create(name=grupo)

def clean_reverse_data(apps, schema_editor):
    for grupo in grupos:
        Group.objects.filter(name=grupo).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('geps', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, clean_reverse_data),        
    ]
