# Generated by Django 4.1.7 on 2023-04-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geps', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('senha', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=20, null=True)),
                ('reg_funcional', models.CharField(max_length=100)),
                ('data_cadastro', models.DateTimeField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='instituicao',
            name='bairro',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='cep',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='email_responsavel',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='endereco',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='estado',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='municipio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='nome_responsavel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='numero',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='senha',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='telefone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='telefone_responsavel',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
