# Generated by Django 4.1.7 on 2023-05-01 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("geps", "0002_docente_estado_instituicao_disponibilidadedocente_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instituicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=200, null=True)),
                ("numero", models.CharField(max_length=10, null=True)),
                ("bairro", models.CharField(default="", max_length=50, null=True)),
                ("municipio", models.CharField(max_length=100, null=True)),
                ("estado", models.CharField(max_length=2, null=True)),
                ("cep", models.CharField(max_length=10, null=True)),
                ("email", models.CharField(max_length=150, null=True)),
                ("telefone", models.CharField(max_length=20, null=True)),
                ("nome_responsavel", models.CharField(max_length=100, null=True)),
                ("email_responsavel", models.CharField(max_length=150, null=True)),
                ("telefone_responsavel", models.CharField(max_length=20, null=True)),
                ("senha", models.CharField(default="", max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name="estado",
            name="sigla",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.CreateModel(
            name="Demanda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diaSemana",
                    models.CharField(
                        choices=[
                            ("Segunda-Feira", "Segunda-Feira"),
                            ("Terça-Feira", "Terça-Feira"),
                            ("Quarta-Feira", "Quarta-Feira"),
                            ("Quinta-Feira", "Quinta-Feira"),
                            ("Sexta-Feira", "Sexta-Feira"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        choices=[
                            ("Manhã", "Manhã"),
                            ("Tarde", "Tarde"),
                            ("Noite", "Noite"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "instituicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geps.instituicao",
                    ),
                ),
            ],
        ),
    ]
