# Generated by Django 4.1.7 on 2023-05-02 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("geps", "0003_instituicao_alter_disponibilidadedocente_diasemana_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisponibilidadeBairro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bairro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="geps.bairro"
                    ),
                ),
                (
                    "docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="geps.docente"
                    ),
                ),
            ],
        ),
    ]
