# Generated by Django 4.1.7 on 2023-05-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geps", "0004_disponibilidadebairro"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="disponibilidadebairro",
            constraint=models.UniqueConstraint(
                fields=("docente", "bairro"), name="docente_bairro"
            ),
        ),
    ]
