# Generated by Django 4.1.7 on 2023-04-03 12:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geps', '0004_professor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Professor',
            new_name='reg_funcional',
        ),
    ]
