# Generated by Django 4.1.7 on 2023-04-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geps', '0005_rename_professor_reg_funcional'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reg_funcional',
        ),
    ]
