# Generated by Django 4.1.7 on 2023-05-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geps", "0005_disponibilidadebairro_docente_bairro"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="disponibilidaderegiao",
            constraint=models.UniqueConstraint(
                fields=("docente", "regiao"), name="docente_regiao"
            ),
        ),
    ]
