# Generated by Django 4.1.7 on 2023-08-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geps', '0003_instituicao_alter_estado_sigla_demanda'),
        ('geps', '0006_disponibilidaderegiao_docente_regiao'),
    ]

    operations = [
    ]
