# Generated by Django 4.2.6 on 2024-03-19 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geps', '0007_merge_20230824_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegiaoMetropolitana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegiaoMetropolitana', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cidade',
            name='lng',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cidade',
            name='regmet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regiao', to='geps.regiaometropolitana'),
        ),
    ]
