# Generated by Django 4.2.6 on 2024-03-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geps', '0008_regiaometropolitana_cidade_lat_cidade_lng_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regiaometropolitana',
            options={'ordering': ['RegiaoMetropolitana']},
        ),
    ]
