# Generated by Django 4.2.6 on 2024-03-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geps', '0009_alter_regiaometropolitana_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regioes',
            name='cidade',
        ),
    ]
