# Generated by Django 4.1.7 on 2024-03-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geps', '0010_remove_regioes_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='sigla',
            field=models.CharField(max_length=2, null=True, unique=True),
        ),
    ]
