# Generated by Django 4.2.6 on 2024-03-19 12:05

from django.db import migrations
import csv

# TODO
def load_data():
    pass

# TODO
def empty_data():
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('geps', '0010_remove_regioes_cidade'),
    ]

    operations = [
        migrations.RunPython(load_data, reverse_code=empty_data)
    ]
