# Generated by Django 4.2.6 on 2024-03-19 12:05

from django.db import migrations
# import csv
import duckdb, os
# from geps.models import Estado

# TODO
def load_data(apps,schema_editor):
    # pass
    reg_met_model=apps.get_model('geps', 'RegiaoMetropolitana')
    this_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), 'source_data'))
    myduck=duckdb.connect(this_dir + "/cidades_completo.duckdb")
    reg_mets=myduck.execute("select distinct RegiaoMetropolitana from cidades").fetchall()
    for reg_met in reg_mets:
        # print(reg_met[0])  # depuração de inserção
        reg_met_model.objects.create(RegiaoMetropolitana = reg_met[0])

# TODO
def empty_data(apps,schema_editor):
    reg_met_model=apps.get_model('geps', 'RegiaoMetropolitana')
    reg_met_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('geps', '0012_carga_inicial_estados'),
    ]

    operations = [
        migrations.RunPython(load_data,empty_data)
    ]
