# Generated by Django 4.1.7 on 2024-03-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geps', '0014_carga_inicial_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiaometropolitana',
            name='RegiaoMetropolitana',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='cidade',
            constraint=models.UniqueConstraint(fields=('nome', 'estado', 'regmet'), name='CidadeUnica'),
        ),
    ]
