# Generated by Django 4.1.7 on 2024-03-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geps', '0017_carrega_bairros_cotia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bairro',
            options={'ordering': ['nome', 'cidade']},
        ),
    ]
